/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enrollment {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface EnrollmentPublic {
  'id' : bigint,
  'name' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'adminDeleteAllEnrollments' : ActorMethod<[string], undefined>,
  'deleteEnrollment' : ActorMethod<[bigint, string], undefined>,
  'getAllEnrollments' : ActorMethod<[string], Array<Enrollment>>,
  'getEnrollment' : ActorMethod<[bigint, string], Enrollment>,
  'getPublicEnrollments' : ActorMethod<[], Array<EnrollmentPublic>>,
  'getTotalEnrollments' : ActorMethod<[], bigint>,
  'submitEnrollment' : ActorMethod<[string, string, string], bigint>,
  'updateEnrollment' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];