/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Enrollment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const EnrollmentPublic = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'adminDeleteAllEnrollments' : IDL.Func([IDL.Text], [], []),
  'deleteEnrollment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllEnrollments' : IDL.Func([IDL.Text], [IDL.Vec(Enrollment)], ['query']),
  'getEnrollment' : IDL.Func([IDL.Nat, IDL.Text], [Enrollment], ['query']),
  'getPublicEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentPublic)], ['query']),
  'getTotalEnrollments' : IDL.Func([], [IDL.Nat], ['query']),
  'submitEnrollment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateEnrollment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Enrollment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const EnrollmentPublic = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'adminDeleteAllEnrollments' : IDL.Func([IDL.Text], [], []),
    'deleteEnrollment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllEnrollments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getEnrollment' : IDL.Func([IDL.Nat, IDL.Text], [Enrollment], ['query']),
    'getPublicEnrollments' : IDL.Func(
        [],
        [IDL.Vec(EnrollmentPublic)],
        ['query'],
      ),
    'getTotalEnrollments' : IDL.Func([], [IDL.Nat], ['query']),
    'submitEnrollment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateEnrollment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };